<?php


require_once './vendor/autoload.php';


class TestLogin extends PHPUnit_Extensions_Selenium2TestCase
{
    public function setUp()
    {
        //$this->setHost('localhost');
        //$this->setPort(4444);
        //parent::setUp(); // TODO: Change the autogenerated stub
        //$this->setBrowser('firefox');
        //$this->setBrowserUrl('http://localhost/remitasia-example/selenium');
        $this->setBrowser('firefox');
        $this->setBrowserUrl('http://www.google.com/');
    }

    public function testTitle()
    {
        $this->url('http://www.google.com/');
        $this->assertEquals('Google', $this->title());
    }

//    public function testHasLoginForm()
//    {
//        $this->url('index.php');
//        $username = $this->byName('username');
//        $password = $this->byName('password');
//
//        $this->assertEquals('', $username->value());
//        $this->assertEquals('', $password->value());
//    }
}